[package]
name = "rust7z"
version = "0.2.0"
license = "WTFPL"
authors = ["nyfair <nyfair2012@gmail.com>"]
repository = "https://github.com/nyfair/rust7z"

description = "7-zip bindings for Rust"
build = "build.rs"

[build-dependencies]
cc = "1.0"
